FORMAT: 1A
HOST: http://apics.oracle.com:8001/apiEnergy

# apiEnergy - Energy Consumption API

API to get details on the energy consumption made by a customer

## Current month usage [/usage/current/month/{account_number}]
+ Parameters
    + account_number (number) - Customer's account number

### Gets current month usage [GET]
Returns the user usage of energy for the **CURRENT** month.

+ Response 200 (application/json)

        {
            "account_number": "12345",
            "name": "John",
            "gas_usage": "1 Btu",
            "gas_cost": "$ 1",
            "electricity_usage": "1 kW",
            "electricity_cost": "$ 1",
            "environment": "US 1",
            "serviceID": "12345"
        }
        
## Last month usage [/usage/last/month/{account_number}]
+ Parameters
    + account_number (number) - Customer's account number

### Gets last month usage [GET]
Returns the user usage of energy for the **LAST** month.

+ Response 200 (application/json)

        {
            "account_number": "12345",
            "name": "John",
            "gas_usage": "1 Btu",
            "gas_cost": "$ 1",
            "electricity_usage": "1 kW",
            "electricity_cost": "$ 1",
            "environment": "US 1",
            "serviceID": "1234"
        }

## Estimate usage [/estimate/{account_number}]
+ Parameters
    + account_number (number) - Customer's account number

### Calculates the estimate of usage [GET]
Returns an estimate for customer's energy usage.

+ Response 200 (application/json)

        {
          "account_number": "12345",
          "name": "John Smith",
          "gas_estimate_usage": "1 Btu",
          "gas_estimate_cost": "$ 1.00",
          "electricity_estimate_usage": "1 kW",
          "electricity_estimate_cost": "$ 1.00",
          "environment": "US 1",
          "serviceID": "7777"
        }